language: c
# whitelist
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libc6:i386
  - sudo apt-get install -y xorg xserver-xorg-video-dummy
  - wget http://www.eecs.berkeley.edu/~pullin/travis/xorg.conf
  - Xorg -noreset -logfile ./10.log -config ./xorg.conf :10 &

install:
 - cd ..
 - wget http://www.eecs.berkeley.edu/~pullin/travis/microchip-complete.tar.gz
 - tar xzf microchip-complete.tar.gz

# Setup step, get PIC gcc compiler and libs
before_script:
 - git clone https://github.com/biomimetics/imageproc-lib
 - git clone https://github.com/biomimetics/imageproc-settings

# Change this to your needs
script:
- pwd
- ./roach/rebuild.sh